PlacesDict = {	'ATM': "ATM",
				'UZ.GOV.UA': "UZ tickets",
				'ALIBABA.COM': "Ali express",
				'20041103': "Dinner (cafe)",
				'WEST LINE': "WEST LINE",
				'S1K30P72': "suhofrukt15",
				'A0900140': "ATM",
				'A0900050': "ATM",
				'DOBROBUT': "DOBROBUT",
				'WWW.PORTMONE.COM.UA': "PORTMONE",
				'VARUS': "VARUS",
				'PLANETA-KINO': "PLANETA-KINO",
				'VITALUX': "Apteka VITALUX",
				'WOG': "AZS 'WOG'",
				'Blizenko': "Blizenko Lvov",
				'BLYZENKO': "Blizenko Lvov",
				'EVERHOUR': "EVERHOUR",
				'Lego': "Lego",
				'Rukavichka': "Rukavichka Lvov",
				'CHICCO': "CHICCO",
				'MAGAZIN1035': "Novus",
				'S1LV0UAK': "Silpo",
				'DZHUNA': "Mega Market",
				'IZUMINKA': "Roshen",
				'NEXT': "NEXT",
				'ALERGO' : "Dinner (cafe)",
				'PRAVDA' : "Lviv - Pravda beerplace",
				'R0153789' : "Lviv - Kopalna",
				'R0165717' : "Lviv - Kopalna",
				'TOV MED TZENTR NASHA R' : "Ingo clinics",
				'S1872449' : "Ingo clinics",
				'SOKRAT' : "SOKRAT store",
				'APTEKA N64' : "Apteka N64",
				'APTEKA NIZKIH CIN' : "Apteka 'nizkih tsen'",
				'APTEKA NIZKIKH TSEN' : "Apteka 'nizkih tsen'",
				'WAKEUP COFFEE' : "Coffee",
				'R0178947' : "Coffee",
				'Aptek34' : "Apteka 34",
				'TOV ELEGANT GR APTEKA' : "Apteka",
				'KafeFransyua' : "Fransua",
				'Apteka1214FYIS7PQX3X00' : "Apteka",
				'BROCARD' : "Brocard",
				'MAG.ROZUMNA DYTYNA' : "'Rozumna Dytyna'",
				'SHELL AZS' : "AZS 'Shell'",
				'KNYZHKOVYI MAHAZYN LIT' : "bookshop 'Litera'",
				'McDonald' : "Dinner (mc)",
				'SILPO' : "Silpo",
				'VARENYCHNA' : "Cafe 'Varenichna'"
				}